// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.unisinos.unitunes.domain;

import com.unisinos.unitunes.domain.Academic;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Academic_Roo_Configurable {
    
    declare @type: Academic: @Configurable;
    
}
